Alse swap freeworld vdpau

diff --git a/installJRMC b/installJRMC
--- a/installJRMC
+++ b/installJRMC
@@ -566,6 +566,18 @@ installMesa() {
                     "${PKG_INSTALL[@]}" mesa-va-drivers-freeworld
                 fi
             fi
+            if ! "${PKG_QUERY[@]}" mesa-vdpau-drivers-freeworld &>/dev/null; then
+                if "${PKG_QUERY[@]}" mesa-vdpau-drivers &>/dev/null; then
+                    if ! execute sudo dnf swap -y \
+                        mesa-vdpau-drivers \
+                        mesa-vdpau-drivers-freeworld; then
+                        err "Package swap failed!"
+                        return 1
+                    fi
+                else
+                    "${PKG_INSTALL[@]}" mesa-va-drivers-freeworld mesa-vdpau-drivers-freeworld
+                fi
+            fi
             ;;
     esac
 }
